import { Navbar } from "@/components/Navbar";

import "@/styles/globals.css";
import Providers from "./providers";

export const metadata = {
    title: "Frontend example",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="min-h-screen">
                <Providers>
                    <Navbar />
                    <main className="w-full p-4 md:p-8 lg:p-12 xl:p-14 2xl:p-16">{children}</main>
                </Providers>
            </body>
        </html>
    );
}
