version: '3.9'

networks:
    frontend-network:
        driver: bridge
    backend-network:
        driver: bridge
    graylog-network:
        driver: bridge

volumes:
    mongodbData:
        driver: local

services:
    backend:
        hostname: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
            args:
                - NODE_ENV=${NODE_ENV}
                - PORT=${BACKEND_PORT}
        networks:
            - backend-network
        depends_on:
            - mongodb
        links:
            - mongodb
        profiles:
            - full
            - backend-proxy

    mongodb:
        hostname: mongodb
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        networks:
            - backend-network
        volumes:
            - mongodbData:/data/db
        ports:
            - 27017:27017
        profiles:
            - full
            - backend-proxy

    nginx:
        hostname: proxy
        build: ./nginx
        networks:
            - frontend-network
            - backend-network
        links:
            - frontend
            - backend
        ports:
            - 8888:80
        profiles:
            - full
            - backend-proxy

    frontend:
        hostname: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                - NODE_ENV=${NODE_ENV}
                - PORT=${FRONTEND_PORT}
        networks:
            - frontend-network
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        profiles:
            - full

    mongo:
        image: mongo:5.0.13
        networks:
            - graylog-network
        profiles:
            - full

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        deploy:
            resources:
                limits:
                    memory: 1g
        networks:
            - graylog-network
        profiles:
            - full

    graylog:
        image: graylog/graylog:5.0
        environment:
            # CHANGE ME (must be at least 16 characters)!
            - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
            # Password: admin
            - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            # - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
        entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
        networks:
            - backend-network
            - graylog-network
        depends_on:
            - mongo
            - elasticsearch
        ports:
            # Graylog web interface and REST API
            - 9000:9000
            # Syslog TCP
            - 1514:1514
            # Syslog UDP
            - 1514:1514/udp
            # GELF TCP
            - 12201:12201
            - 5555:5555
            # GELF UDP
            - 12201:12201/udp
            - 5555:5555/udp
        profiles:
            - full
